# Generated by Django 3.0.3 on 2020-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
    ]
