# Generated by Django 3.0.3 on 2020-06-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0003_auto_20200607_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics'),
        ),
    ]
