# Generated by Django 3.0.3 on 2020-06-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0006_auto_20200607_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
