# Generated by Django 3.0.3 on 2020-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0008_auto_20200608_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeehouseuser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
