# Generated by Django 3.0.3 on 2020-06-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstweb', '0011_auto_20200614_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stud',
        ),
    ]
